### ISSUE TITLE
Missing Layers in Legend and No Base Layer Tile Requests Sent

### ISSUE THREAD

**Issue by Crispin-at-Linknode** [jumpinjackie/mapguide-react-layout#1401] opened 2022-07-05 08:03 UTC
I have a map with Base Layer Groups that is not loading properly (links below).

There is NO OPERATION=GetTileImage request sent to the mapserver at all when the layout loads.  And the legend is only showing a subset of the available layers.  I can see more when searching, but even then, toggling the base map group does not send a server request.
I am guessing something is stopping the layers list loading, which is then not reading down to the Base Layers and hence the local layer cache of the MapDefinition will always be incomplete?

I also get a lot of "failed to Fetch" errors in the viewer -- it would be great to have some logging or setting that would allow a detailed error to be shown when this occurs.

React Layout without Tiled Layers
(click the <search> icon in the legend to expand the groups and layers, but still not properly showing th 

https://webgis.east-ayrshire.gov.uk/mapguide31/viewer/sidebar.html?resource=Library://EastAyrshire/Layouts/EACInternet_TileSet.WebLayout

You can see how it should look with the AJAX version:

https://webgis.east-ayrshire.gov.uk/mapguide31/mapviewerajax/?WEBLAYOUT=Library://EastAyrshire/Layouts/EACInternet_TileSet.WebLayout

**Comment by jumpinjackie** [comment] 2022-07-05 15:17
What release/version of the viewer are you using?

**Comment by Crispin-at-Linknode** [comment] 2022-07-05 16:12
It was only installed a month or so ago -- it was either the current GitHub release or built from source... I don't think there were many significant commits between the release and 5 weeks ago.

**Comment by Crispin-at-Linknode** [comment] 2022-07-08 12:29
Thanks -- if you ever do a blog about getting started debugging with VS or VS Code and the viewer I could probably get started and find a way in, but a TypeScript project just feels too alien at the moment

**Comment by jumpinjackie** [comment] 2022-07-19 10:22
An update.

I found the likely culprit. It is currently not looking like the viewer is at fault, but rather the `CREATERUNTIMEMAP` operation.

The `Layer` collection in the response only has 11 items,  but when I look at the map definition itself there is clearly way more. So for reasons currently unknown, the `CREATERUNTIMEMAP` operation is skipping a whole bunch of layers. 

The legend constructs its tree structure based on this (incomplete) information which is why there's only 6 groups visible.

Made a ticket on the MG side for you to follow: https://trac.osgeo.org/mapguide/ticket/2846

**Comment by Crispin-at-Linknode** [comment] 2022-07-19 10:48
Interesting... but the classic AJAX viewer constructs the legend as expected - doesn't use the same CreateRuntimeMap operation I guess.

If I knew what oddity was in one of the layers or definition I could try and adapt the layer or .MapDefinition as putting a server hotfix in place will be a bit more of a PITA !

Thanks for updating.

**Comment by Crispin-at-Linknode** [comment] 2022-07-20 14:05
Yes, that's excellent news - much easier to do a layer rename than a patch and lowers the severity with a reasonable workaround. Many thanks

**Comment by jumpinjackie** [comment] 2022-07-20 14:18
Ok, closing as the problem is now solely on the MG side via the referenced ticket

**Closed by jumpinjackie** 2022-07-20 14:18 UTC
