### ISSUE TITLE
v0.11.0 test report+suggestions

### ISSUE THREAD

**Issue by RenoSun** [jumpinjackie/mapguide-react-layout#540] opened 2018-02-21 00:45 UTC
1. Still displayed all the tiled Base Layers initially regardless if the Base Layers are initially displayed in the map or not

2. Partial Application State 
(Enhancement) 
- Save the base map option selection as part of the application state
- Save the tiled Base Layers On/Off status as part of the application state
- Save the MapTip On/Off status as part of the application state

- (Bug maybe?)Selection panel do not display the selection info, although the selection layer is shown and saved as partial application state 

3. Adding external WMS layers is so powerful. Love it.
![image](https://user-images.githubusercontent.com/5566783/36457145-66c7b226-165d-11e8-80a7-953bb9a121e8.png)

4. ShareLinkToView is working very well. One suggestion that I may have is to have "Copy" and "Share" buttons for users to copy and share the URL even easier.

5. Measure Segment Display is working great.

6. Selection Panel
- The HTML property values are able to be presented as actual HTML by change the viewer mount options
` ...viewer.mount(el, {
                layout: "turquoise-yellow",
                selectionSettings: {
                    allowHtmlValues: true,
},...`
- (Bug maybe?) The property with HTML values will always be displayed at the bottom of the selection panel regardless of the property display order setting.
![image](https://user-images.githubusercontent.com/5566783/36456231-b9c0d980-1658-11e8-9519-b35a080b14be.png)
![image](https://user-images.githubusercontent.com/5566783/36456281-f6ecc6e8-1658-11e8-8bb0-93dea0a96605.png)

- (Bug maybe?) The Previous Feature Button icon is now a buffer icon.
![image](https://user-images.githubusercontent.com/5566783/36456317-34ad8af8-1659-11e8-9f50-a0b00bf90e90.png)

- (Bug) Next/Previous Feature will displayed the highlight incorrectly sometimes when the user zoom out/in on the map.
![image](https://user-images.githubusercontent.com/5566783/36456458-dd5bc534-1659-11e8-9733-36105e847b05.png)

- (Bug) Next/Previous Feature will displayed the highlight the feature not matched the current feature selection info. EX: Feature Address: 693/695 PRIMROSE AVE, but it highlight the feature with address: 675 PRIMROSE AVE
![image](https://user-images.githubusercontent.com/5566783/36456595-7a5d8598-165a-11e8-9831-52514fc08b5e.png)

- (Suggestion) When the user use Zoom to selected feature, it will be nice to also highlighted the selected feature too. Therefore, the user will be less confused sometimes due to the complexity of geometries of the features.
 
7. Drawing/Digitization improvements + Select Polygon  works great. Love the free-hand drawing, and UNDO feature!

8. The template Aqua
-  (Enhancement)  Make Legend, Selection, and Task Panes resizable.

9. (Bug maybe?)
Task Pane Go Back button icon
![image](https://user-images.githubusercontent.com/5566783/36456881-11d35140-165c-11e8-8946-3fb95ca14617.png)

10. Resizable sidebar is working.

Thanks for all your hard working Jackie!

**Comment by jumpinjackie** [comment] 2018-02-21 10:59
Re: Icons

I cannot reproduce this. I can only suspect you are holding on to a stale `dist/stdassets/images/icons.png` sprite somewhere.

**Comment by jumpinjackie** [comment] 2018-02-21 11:51
Re: Property panel ordering

I can't seem to reproduce this one. Whatever order the HTML property is at seems to be respected for me.

![html_order](https://user-images.githubusercontent.com/563860/36478673-b96b93a6-1759-11e8-9e71-1e49be710913.png)

**Comment by jumpinjackie** [comment] 2018-02-21 12:01
Re: Selection (Partial Application State)

The problem is that we can recover/reuse the runtime maps from the session id. If it has selections they will render on the map, but (surprisingly) there's no API in the current mapagent to pull the current selection XML from the current session id. Without this ability the reloaded client knows nothing about the selection and selected features of the runtime maps we're recovering from until the user does a new map selection.

We cannot just shove selection state wholesale into the URL either because a URL can only be so long and we have a limited URL size budget that won't accommodate really large selections (some applications will go there).

We could bite the bullet and put the client-side selected features into local storage and restore it from there, but that sounds dirty. Given a mapname and a session id, the MapGuide Server should be able to provide all the necessary information to the client viewer to reconstruct itself.

It's not a hard problem per se, it more weighing the pros/cons of all the different ways to solve this.

**Comment by jumpinjackie** [comment] 2018-02-21 12:02
Re: Base Layers still initially showing

I am bit confused. Are you referring to tiled base layers of a Map Definition or MG tileset and not base layers ala Bing/OSM/etc?

**Comment by RenoSun** [comment] 2018-02-21 17:03
Re: Icons
Yeah, after I had cleaned the browser cookies and cached images, the icons were shown correctly now 👍 

Re: Selection (Partial Application State)
I see. I think it can be easily done by using mapguide-rest to pull the current selection XML from the current session id, but it's not part of mapguide-react-layout . If the user desire or need to share their selections and current map view with another user, he/she will need to implement something by using mapguide-rest on client-side 

Re: Base Layers still initially showing
I meant Base Layer Groups (Tiled)

I set up not to display initially on the map, but the mapguide-react-layout will display every tiled Base Layer Groups initially regardless of my initial setting.
![image](https://user-images.githubusercontent.com/5566783/36494029-cefb74bc-16e5-11e8-8d56-4929efa21d84.png)

![image](https://user-images.githubusercontent.com/5566783/36494075-f368226e-16e5-11e8-8de2-3e6307299ee5.png)

**Comment by jumpinjackie** [comment] 2018-02-23 11:40
*sigh* Of course I had already solved this problem in mapguide-rest! 

Sadly, I cannot take a server-side dependency on mapguide-rest as synergistic having both together may be. mapguide-react-layout is intended to work on a standard MapGuide installation.

**Comment by jumpinjackie** [comment] 2018-08-29 16:56
I've lost track of what's actually fixed now and what isn't so I'm closing this. Feel free to re-create the un-fixed bits as individual issues.

**Closed by jumpinjackie** 2018-08-29 16:56 UTC
